//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorPassword
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amistad
    {
        public int idAmistad { get; set; }
        public int idJugadorAmigo { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public Nullable<System.DateTime> fechaRespuesta { get; set; }
        public int FKidJugador { get; set; }
    
        public virtual Jugador Jugador { get; set; }
    }
}
