//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorPassword
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePartida
    {
        public int idDetallePartida { get; set; }
        public int FKidPartida { get; set; }
        public int FKidJugador { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual Partida Partida { get; set; }
    }
}
