//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugador()
        {
            this.Amistad = new HashSet<Amistad>();
            this.DetalleLogro = new HashSet<DetalleLogro>();
            this.DetallePartida = new HashSet<DetallePartida>();
        }
    
        public int idJugador { get; set; }
        public string nombreUsuario { get; set; }
        public string descripcion { get; set; }
        public string rutaImagen { get; set; }
        public Nullable<int> FKidAcceso { get; set; }
        public Nullable<int> FKidEstadistica { get; set; }
    
        public virtual Acceso Acceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Amistad> Amistad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleLogro> DetalleLogro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePartida> DetallePartida { get; set; }
        public virtual Estadistica Estadistica { get; set; }
    }
}
